{% set name = "susi" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/susi-{{ version }}.zip
  sha256: a47ec6ac5521f9538208d654ed335e8e61336299d4cd7b9ea7854c240e0f1948

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - joblib >=0.13.0
    - numpy >=1.18.5
    - python >=3.9
    - scikit-learn >=0.21.1
    - scipy >=1.3.1
    - tqdm >=4.45.0
    - matplotlib-base >=3.9.0
    - seaborn >=0.11.0
    - pandas >=1.1.5

test:
  imports:
    - susi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixriese/susi
  summary: Python package for unsupervised, supervised and semi-supervised self-organizing maps (SOM)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixriese
