{% set name = "susi" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/susi-{{ version }}.zip
  sha256: 688f396f77026bb71df04670bc1f41b5b2d7f95d4187885ff3f5e0b7e88242d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - joblib >=0.13.0
    - numpy >=1.18.5
    - python >=3.9
    - scikit-learn >=0.21.1
    - scipy >=1.3.1
    - tqdm >=4.45.0
    - matplotlib-base >=3.7.2
    - seaborn >=0.11.0
    - pandas >=1.1.5

test:
  imports:
    - susi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixriese/susi
  summary: Python package for unsupervised, supervised and semi-supervised self-organizing maps (SOM)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixriese
