{% set name = "susi" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/susi-{{ version }}.zip
  sha256: 62e8ce5d38f13f361a2b5f756128f1e577316e3ba2a791e8af1ccf6122750d5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - joblib >=0.13.0
    - numpy >=1.18.5
    - python >=3.7
    - scikit-learn >=0.21.1
    - scipy >=1.3.1
    - tqdm >=4.45.0
    - matplotlib-base >=3.7.2
    - seaborn >=0.11.0
    - pandas >=1.1.5

test:
  imports:
    - susi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixriese/susi
  summary: Python package for unsupervised, supervised and semi-supervised self-organizing maps (SOM)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixriese
